[package]
name = "speck-vz"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]

[dependencies]
speck-core = { path = "../speck-core" }
objc2 = { version = "0.6", features = ["objc2-proc-macros"] }
objc2-foundation = { version = "0.3", features = ["NSURL", "NSError", "NSFileHandle"] }
objc2-virtualization = { version = "0.3", features = [
    "VZVirtualMachineConfiguration",
    "VZVirtualMachine",
    "VZVirtualMachineDelegate",
    "VZBootLoader",
    "VZLinuxBootLoader",
    "VZPlatformConfiguration",
    "VZGenericPlatformConfiguration",
    "VZEntropyDeviceConfiguration",
    "VZVirtioEntropyDeviceConfiguration",
    "VZSocketDeviceConfiguration",
    "VZSocketDevice",
    "VZVirtioSocketDeviceConfiguration",
    "VZVirtioSocketDevice",
    "VZVirtioSocketConnection",
    "VZFileHandleNetworkDeviceAttachment",
    "VZVirtioNetworkDeviceConfiguration",
    "VZNetworkDeviceAttachment",
    "VZNetworkDeviceConfiguration",
    "VZMACAddress",
    "block2",
    "dispatch2",
    "VZStorageDeviceConfiguration",
    "VZVirtioBlockDeviceConfiguration",
    "VZStorageDeviceAttachment",
    "VZDiskImageStorageDeviceAttachment",
    "VZDirectorySharingDeviceConfiguration",
    "VZDirectoryShare",
    "VZVirtioFileSystemDeviceConfiguration",
    "VZSharedDirectory",
    "VZSingleDirectoryShare",
    "VZConsoleDeviceConfiguration",
    "VZConsolePortConfiguration",
    "VZVirtioConsoleDeviceConfiguration",
    "VZVirtioConsolePortConfiguration",
    "VZVirtioConsolePortConfigurationArray",
    "VZSerialPortAttachment",
    "VZFileSerialPortAttachment",
] }
block2 = "0.6"
dispatch2 = "0.3"
libc = "0.2"
socket2 = { version = "0.5", features = ["all"] }
thiserror = "2"
tokio = { version = "1.52", features = ["sync"] }
tracing = "0.1"

speck-net = { path = "../speck-net" }

[dev-dependencies]
containerd-client = "0.9.0"
speck-net = { path = "../speck-net" }
smoltcp = "0.13"
tokio = { version = "1.52", features = ["rt", "macros"] }
