[package]
name = "speck-vz"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]

[dependencies]
speck-core = { path = "../speck-core" }
objc2 = { version = "0.6", features = ["objc2-proc-macros"] }
objc2-foundation = { version = "0.3", features = ["NSURL", "NSError"] }
objc2-virtualization = { version = "0.3", features = [
    "VZVirtualMachineConfiguration",
    "VZVirtualMachine",
    "VZLinuxBootLoader",
    "VZVirtualMachineDelegate",
] }
block2 = "0.6"
dispatch2 = "0.3"
thiserror = "2"
tokio = { version = "1.52", features = ["sync"] }
