syntax = "proto3";

package buildkit.control;

import "google/protobuf/timestamp.proto";

service Control {
    rpc Solve(SolveRequest) returns (SolveResponse);
    rpc Status(StatusRequest) returns (stream StatusResponse);
    rpc Session(stream BytesMessage) returns (stream BytesMessage);
}

message SolveRequest {
    string ref = 1;
    Definition definition = 2;
    string exporter_deprecated = 3;
    map<string, string> exporter_attrs_deprecated = 4;
    string session = 5;
    string frontend = 6;
    map<string, string> frontend_attrs = 7;
    CacheOptions cache = 8;
    repeated string entitlements = 9;
    map<string, Definition> frontend_inputs = 10;
    bool internal = 11;
    repeated Exporter exporters = 13;
    bool enable_session_exporter = 14;
    string source_policy_session = 15;
    int64 compatibility_version = 16;
    bool proxy_network = 17;
}

message Definition {
    repeated bytes def = 1;
}

message CacheOptions {
    map<string, string> export_attrs = 1;
    repeated string import_refs = 2;
}

message Exporter {
    string type = 1;
    map<string, string> attrs = 2;
}

message SolveResponse {
    map<string, string> exporter_response = 1;
}

message StatusRequest {
    string ref = 1;
}

message StatusResponse {
    repeated VertexLog logs = 1;
}

message VertexLog {
    bytes vertex = 1;
    int64 stream = 2;
    bytes msg = 3;
    google.protobuf.Timestamp timestamp = 4;
}

message BytesMessage {
    bytes data = 1;
}
