syntax = "proto3";

package buildkit.control;

import "google/protobuf/timestamp.proto";

service Control {
    rpc Solve(SolveRequest) returns (SolveResponse);
    rpc Status(StatusRequest) returns (stream StatusResponse);
}

message SolveRequest {
    string ref = 1;
    string frontend = 3;
    map<string, string> frontend_attrs = 4;
    CacheOptions cache = 5;
    repeated ExportRequest exports = 15;
}

message CacheOptions {
    map<string, string> export_attrs = 1;
    repeated string import_refs = 2;
}

message ExportRequest {
    string type = 1;
    map<string, string> attrs = 2;
}

message SolveResponse {}

message StatusRequest {
    string ref = 1;
}

message StatusResponse {
    repeated VertexLog logs = 1;
}

message VertexLog {
    bytes vertex = 1;
    int64 stream = 2;
    bytes msg = 3;
    google.protobuf.Timestamp timestamp = 4;
}
