[package]
name = "speck-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "spk"
path = "src/main.rs"

[dependencies]
anyhow = "1"
anstream = "1.0.0"
clap = { version = "4.6.1", features = ["derive"] }
clap_complete = "4.6"
crossterm = "0.29.0"
futures = "0.3"
http-body-util = "0.1"
hyper = { version = "1.10.1", features = ["full"] }
hyper-util = { version = "0.1.20", features = ["client", "client-legacy", "tokio"] }
indicatif = "0.18.4"
ratatui = { version = "0.30.2", features = ["crossterm"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
speck-core = { path = "../speck-core" }
speck-dockerd = { path = "../speck-dockerd" }
speck-net = { path = "../speck-net" }
speck-vz = { path = "../speck-vz" }
tokio = { version = "1.52.3", features = ["full"] }
tar = "0.4"
tower = "0.5"
tracing = "0.1.44"
walkdir = "2"
tracing-indicatif = "0.3.14"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
